baseurl: "" 
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: "Lumina"
description: "Lumina（ルミナ）は、プライバシーと表現の自由を守るためのソフトウェアとハードウェアを開発するサイバーセキュリティグループです。"
keywords: "Lumina, プライバシー, セキュリティ, サイバーセキュリティ, 暗号化, 匿名性, 表現の自由"
url: "https://lumina-group.jp"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
collections:
  news:
    output: true
    permalink: /news/:name/

en:
  title: "Lumina"
  description: "Lumina is a cybersecurity group that develops software and hardware to protect privacy and freedom of expression."
  keywords: "Lumina, privacy, security, cybersecurity, encryption, anonymity, freedom of expression"