baseurl: "" 
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: "Lumina"
url: "https://lumina-group.jp"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
collections:
  news:
    output: true
    permalink: /news/:name/